import React, { useMemo } from 'react';
import { useAppState } from '../../context/AppStateContext';

/**
 * PUBLIC_INTERFACE
 * ReportPreview - Shows grouped preview data with print/PDF friendly wrapper.
 */
export default function ReportPreview() {
  const { reportPreview, loading, error, rules } = useAppState();
  const data = reportPreview || [];

  const totals = useMemo(() => {
    const totalGroups = data.length || 0;
    const totalHours = (data || []).reduce((acc, g) => acc + (g.totalHours || 0), 0);
    return { totalGroups, totalHours };
  }, [data]);

  const dateRangeLabel = useMemo(() => {
    switch (rules?.timeframe) {
      case 'this_week': return 'This Week';
      case 'last_week':
      default: return 'Last Week';
    }
  }, [rules]);

  return (
    <section className="report-wrapper" aria-labelledby="preview-title" aria-describedby="preview-desc" data-tour-id="preview">
      <h2 id="preview-title" className="sr-only">Report Preview</h2>
      <p id="preview-desc" className="sr-only">A quick look at how your report will be structured.</p>

      {/* Branded header area visible for print */}
      <header className="report-header" role="presentation" aria-hidden="true">
        <div className="report-header-strip" />
        <div className="report-header-content">
          <div className="report-header-left">
            <div className="report-appname">Weekly Status Report</div>
            <div className="report-meta">
              <span>Ocean Professional</span>
              <span aria-hidden="true">•</span>
              <span>{dateRangeLabel}</span>
            </div>
          </div>
          <div className="report-header-right">
            <div className="report-org">Generated by Weekly Status Report Generator</div>
            <div className="report-date">{new Date().toLocaleString()}</div>
          </div>
        </div>
      </header>

      {/* Report title and meta summary (screen + print) */}
      <div className="op-card report-intro">
        <div className="report-title">Weekly Status Summary</div>
        <div className="report-summary">
          <div><strong>Grouping:</strong> {rules?.grouping || 'assignee'}</div>
          <div><strong>Timeframe:</strong> {dateRangeLabel}</div>
          <div><strong>Totals:</strong> {totals.totalGroups} groups • {totals.totalHours}h</div>
        </div>
      </div>

      {loading && (
        <div className="op-card" role="status" aria-live="polite">
          <p className="op-status">Loading preview…</p>
        </div>
      )}

      {!loading && error && (
        <div className="op-card" role="alert">
          <p className="op-status error">Error loading preview. {error}</p>
        </div>
      )}

      {!loading && !error && (!data || data.length === 0) ? (
        <div className="op-card" style={{ color: 'var(--op-muted)' }} role="status" aria-live="polite">
          No data yet. Upload files to see a preview.
        </div>
      ) : null}

      {!loading && !error && data && data.length > 0 && (
        <div style={{ display: 'grid', gap: 12 }}>
          {data.map((group, i) => (
            <div key={group.group} className="op-card report-group" data-report-group-index={i}>
              <div className="report-group-title">
                <span className="report-group-name">{group.group}</span>
                <span className="report-group-hours">{group.totalHours}h</span>
              </div>
              <div style={{ overflowX: 'auto' }}>
                <table className="op-table report-table" aria-label={`Items for ${group.group}`}>
                  <caption className="sr-only">Tasks grouped by {group.group}</caption>
                  <thead>
                    <tr>
                      <th scope="col">ID</th>
                      <th scope="col">Summary</th>
                      <th scope="col">Hours</th>
                      <th scope="col">Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {group.items.map((item) => (
                      <tr key={item.id}>
                        <td><span style={{ color: 'var(--op-muted)' }}>{item.id}</span></td>
                        <td>{item.summary}</td>
                        <td>{item.hours}h</td>
                        <td>{item.status}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Branded footer for print */}
      <footer className="report-footer" role="contentinfo" aria-label="Report footer">
        <div className="report-footer-content">
          <span>Generated by Weekly Status Report Generator</span>
          <span aria-hidden="true">•</span>
          <span className="print-timestamp">{new Date().toLocaleString()}</span>
          <span aria-hidden="true">•</span>
          <span className="print-page-number">Page <span className="pageNumber"></span></span>
        </div>
      </footer>
    </section>
  );
}
